Import Debian changes 1.11-3
trustedqsl (1.11-3) unstable; urgency=low

  * Rebuild against tqsllib1c2a due to g++ ABI change
  * Hack configure.in not to link directly to OpenSSL and expat and zlib,
    since they aren't used directly (only by tqsllib)

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -273,11 +273,11 @@ LIBRARY_PATH="$LIBRARY_PATH$TQSLLIB:$EXPAT/lib:$ZLIB/lib"
 export LIBRARY_PATH
 
 dnl Checks for libraries.
-AC_CHECK_LIB(z, main, , [ echo -e "\nlibz not found! (Use --with-zlib to correct)"; exit 1 ], -lstdc++)
-AC_CHECK_LIB(expat, main, , [ echo -e "\nlibexpat not found! (Use --with-expat to correct)"; exit 1 ], -lstdc++)
-if test -n "$checkopenssl"; then
-  AC_CHECK_LIB(crypto, main, , [ echo -e "\nlibcrypto not found! (Use --with-openssl to correct)"; exit 1 ], -lstdc++)
-fi
+dnl AC_CHECK_LIB(z, main, , [ echo -e "\nlibz not found! (Use --with-zlib to correct)"; exit 1 ], -lstdc++)
+dnl AC_CHECK_LIB(expat, main, , [ echo -e "\nlibexpat not found! (Use --with-expat to correct)"; exit 1 ], -lstdc++)
+dnl if test -n "$checkopenssl"; then
+  dnl AC_CHECK_LIB(crypto, main, , [ echo -e "\nlibcrypto not found! (Use --with-openssl to correct)"; exit 1 ], -lstdc++)
+dnl fi
 
 if test "$build_os" = "mingw32"; then
 	AC_CHECK_LIB(tqsllibd, main, , [ echo -e "\nlibtqsllib not found! (Use --with-tqsllib to correct)"; exit 1 ], -lstdc++)
